name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - IMMICH_VERSION

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read IMMICH_VERSION
        run: |
          echo "IMMICH_VERSION=$(cat IMMICH_VERSION | tr -d '\n')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if image tag already exists
        run: |
          if docker manifest inspect ghcr.io/urkaz/immich-server-gocryptfs:${{ env.IMMICH_VERSION }} > /dev/null 2>&1; then
            echo "Image tag ${{ env.IMMICH_VERSION }} already exists. Aborting."
            exit 1
          else
            echo "Image tag does not exist. Continuing."
          fi

      - name: Build image
        run: |
          docker build \
            --build-arg IMMICH_VERSION=${{ env.IMMICH_VERSION }} \
            -t ghcr.io/urkaz/immich-server-gocryptfs:latest \
            -t ghcr.io/urkaz/immich-server-gocryptfs:${{ env.IMMICH_VERSION }} \
            .

      - name: Push image
        run: |
          docker push ghcr.io/urkaz/immich-server-gocryptfs:latest
          docker push ghcr.io/urkaz/immich-server-gocryptfs:${{ env.IMMICH_VERSION }}